### ISSUE TITLE
Move off of olafurpg/setup-scala in Actions

### ISSUE THREAD

**Issue by colindean** [target/data-validator#142]
Per https://github.com/olafurpg/setup-scala/issues/49, `olafurpg/setup-scala` is ~unmaintained and there are better options available. We do have a need to compile against JDK8 so we can probably take the recommended route of using the [actions/setup-java](https://github.com/actions/setup-java) action.

**Comment by colindean** [comment]
Another options is to use https://github.com/coursier/setup-action

**Comment by colindean** [comment]
olafurpg/setup-scala is no longer maintained, according to its v14 release notes linked in #149, so we need to move as soon as possible.

This ought to do it and enable removing the extended cache config, too:

```yaml
    - uses: coursier/cache-action@v6
    - uses: coursier/setup-action@v1
      with:
        jvm: adopt:1.8
 ```
