### ISSUE TITLE
Streamline configuration for the same test applied to multiple columns

### ISSUE THREAD

**Issue by phpisciuneri** [target/data-validator#37]
Currently, if I wanted to check for null values in each of the columns (`age`, `occupation`) of a table, the `checks:` section of the configuration file would contain something this:

```yaml
- type: nullCheck
  column: age

- type: nullCheck
  column: occupation
```

Ideally, we should support a more streamlined config.  Something like:

```yaml
- type: nullCheck
  columns: age, occupation
```

We would need to decide how to handle optional parameters in the streamlined case.  One option is that we do not support streamlining if any optional parameters are specified:

```yaml
- type: nullCheck
  column: age
  threshold: 1%

- type: nullCheck
  column: occupation
  threshold: 5%
```

Another option would be to allow additional parameters to be streamlined and applied in the same order as the specified columns:

```yaml
- type: nullCheck
  columns: age, occupation
  thresholds: 1%, 5%
```
