### ISSUE TITLE
createKeySelect log msg is potentially redundant and should not be at error level

### ISSUE THREAD

**Issue by phpisciuneri** [target/data-validator#55]
For example, given:

```yaml
---
numKeyCols: 2
numErrorsToReport: 1
detailedErrors: true

outputs:
  - filename: report.json
    append: false

tables:
  - db: census_income
    table: adult
    checks:
      - type: rangeCheck
        column: age
        minValue: 40
        maxValue: 50
```

In the output you will see:

```
...
...
21/01/14 14:35:32 ERROR ValidatorTable: createKeySelect: age, workclass keyColumns: None
...
...
```

This is not an error.  It is merely informing you what the keyColumns are for `ValidatorQuickCheckError` details.  In the case that the keyColumns are specified in the configuration, you will end up seeing them listed twice.
