### ISSUE TITLE
Add support for variable substitution for `minNumRows` in `rowCount` check

### ISSUE THREAD

**Issue by phpisciuneri** [target/data-validator#58]
We should be able to support the following use case or something analogous to it:

```yaml
---
numKeyCols: 2
numErrorsToReport: 1
detailedErrors: true

vars:
  - name: NUM_ROWS
    value: 1000
  
tables:
  - db: census_income
    table: adult
    checks:
      - type: rowCount
        minNumRows: $NUM_ROWS
```

Currently, trying the above configuration yields a fairly non-descriptive `DecodingFailure`

```
21/01/15 12:24:03 ERROR Main$: Failed to parse config file 'issue.yaml, {}
DecodingFailure(Attempt to decode value on failed cursor, List(DownField(parquetFile), DownArray, DownField(tables)))
```

It is noted in the [documentation](https://github.com/target/data-validator#rowcount) that this is not currently supported.
