### ISSUE TITLE
Thresholds parsed as JSON floats are ignored

### ISSUE THREAD

**Issue by colindean** [target/data-validator#77]
**Describe the bug**

When specifying a check with a threshold that will parse to a JSON float, e.g.

```yaml
threshold: 0.10 # will be ignored
threshold: 10% # works
threshold: "0.10" # works
```

the threshold will be ignored.

**To Reproduce**

Configure a check with:

```yaml
type: nullCheck
column: foo
threshold: 0.10
```

or put that into a test in `NullCheckSpec`.

**Expected behavior**

Thresholds specified as floats should work.
