### ISSUE TITLE
Allow format+options to be passed before Hive query

### ISSUE THREAD

**Issue by colindean** [target/data-validator#78]
We have a use case which necessitates constructing queries a certain way:

```scala
val df = spark.read.format("internal_format").option("database", "foo").load("select * from myTable")
// … Spark magic …
df.write.format("internal_format").option("database", "my_select_database").save()
```

DV doesn't have a way to allow the user to pass arbitrary format or a map of options in this manner. A particular Target-internal use case requires this and DV cannot be used for this use case until these are supported.

A proposed solution is to allow `format: String` and `options: Object|Map[String, String]` properties:

```yaml
tables:
  - db: census_income
    table: adult
    format: internal_format
    options:
      database: census_income
      hive.vectorized.execution.reduce.enabled: "false"
    keyColumns:
      - age
      - occupation
    condition: educationNum >= 5
    checks:
      - type: rowCount
        minNumRows: 50000
```
