### ISSUE TITLE
Release builds for newer versions of Scala and Spark

### ISSUE THREAD

**Issue by colindean** [target/data-validator#84]
**Is your feature request related to a problem? Please describe.**

We currently only ship for Scala 2.11 and Spark 2.3.x.

**Describe the solution you'd like**

We should ship for newer versions in whatever pairs are appropriate.

**Additional context**

https://github.com/sbt/sbt-projectmatrix is probably the right tool for the job.

**Comment by colindean** [comment]
Minimal:

```yaml
groups:
  - spark:
    - 2.3.4
    scala:
    - 2.11.12
```

Max:

```yaml
groups:
  - spark:
    - 2.3.4
    scala:
    - 2.11.12
  - spark:
    - 2.4.8
    - 3.0.3
    - 3.1.3
    scala:
    - 2.12.15
  - spark:
    - 3.2.1
    scala:
    - 2.13.8
```

Spark versions: <https://spark.apache.org/downloads.html>
